### ISSUE TITLE
Error importing a project : missing or invalid csrf_token parameter

### ISSUE THREAD

**Issue by msaby** [OpenRefine/OpenRefine#2239]
**Describe the bug**

I tried to import a project exported from OR3.1 in OR3.3 and  got this error : 

{
code: "error",
message: "Missing or invalid csrf_token parameter"
}

**To Reproduce**
 

**Current Results**
 
**Expected behavior**
 
**Screenshots**
 
**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Version: Chome
 - JRE or JDK Version: JRE 1.8.0_231

**OpenRefine (please complete the following information):**
 - Version: Openrefine 3.3

**Datasets**

**Additional context**

**Comment by wetneb** [comment]
It should be solved in the master branch!

**Comment by msaby** [comment]
Thanks, I think it is this patch?

https://github.com/OpenRefine/OpenRefine/commit/11c778823943f327d865a639116f56e0cc6383fd

So I close the issue

**Comment by AndriiPiatakha** [comment]
Unfortunately - that is not worked for me. Issue in master still exists for me when I create project. Can we reopen this issue?
