### ISSUE TITLE
Editing cells with null values

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#332]
_Original author: benjamin...@gmail.com (February 08, 2011 19:42:08)_

<b>What steps will reproduce the problem?</b>
1. click &quot;edit&quot; on a cell with a null value
2. change the value and apply to all identical cells

<b>What is the expected output? What do you see instead?</b>
One would expect all cells with null values to update. Instead no cells are changed, including the cell from which the edit was made.

<b>What version of Google Refine are you using?</b>
Version 2.0 [r1836]

<b>What operating system and browser are you using?</b>
Windows XP SP3, Chrome 9.0.597.84

<b>Is this problem specific to the type of browser you're using or it happens</b>
<b>in all the browsers you tried?</b>
Same issue using FF 3.6.13

<b>Please provide any additional information below.</b>
Dealing with nulls is generally problematic. Using any of the scripting tools to access null values produces errors. And it would be helpful to be able to differentiate nulls from blanks in the actual grid view of the data.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=332_

**Comment by pmbKK** [comment]
Has there been any progress on this yet? Using OpenRefine 2.7 and still see the same behavior described by @tfmorris. When trying using the "Apply to All Identical Cells" it does not fill that cell, or any of the other identical cells when they are null, and it says Mass edit 0 cells in column X in the history.

**Comment by tfmorris** [comment]
Just to clarify, none of these posts are from me. I just did the import from Google Code. The original author of each message is in the first line of the message (look for italics and From ...)

**Comment by thadguidry** [comment]
Fixed in #1539 and #1598

**Comment by ostephens** [comment]
This is still a problem in 3.0 Beta

Editing a cell which contains either a `null` or a zero length string, and then clicking "Apply to all identical cells" leads to NO edits being made (including the cell you started from).

**Comment by ostephens** [comment]
Just an update - I'm working on this and work in progress is at https://github.com/ostephens/OpenRefine/tree/mass-edit-fix

tl/dr fix #1631 is relatively straightforward, but I'm trying to make tests and fix #1632, #180 and #332 at the same time which is proving more complicated and taking more time

**Comment by ostephens** [comment]
Fixed by #1642
