### ISSUE TITLE
Unable to make schema for own Wikibase: NullPointerException in EditInspector

### ISSUE THREAD

**Issue by Nikerabbit** [OpenRefine/OpenRefine#3354]
### To Reproduce
1. Setup a Wikibase instance with a query service and openrefine
2. Use the query service to download some data (https://tinyurl.com/y5xmdjtw)
3. Try to create a schema to save the (updated) data back

The manifest I am using for testing is:
```
{
  "version": "1.0",
  "mediawiki": {
    "name": "Nimiarkisto (dev)",
    "root": "https://nimiarkisto.nikerabb.it/wiki/",
    "main_page": "https://nimiarkisto.nikerabb.it",
    "api": "https://nimiarkisto.nikerabb.it/w/api.php"
  },
  "wikibase": {
    "site_iri": "http://nimiarkisto.fi/entity/",
    "maxlag": 5,
    "properties": {
      "instance_of": "P31",
      "subclass_of": "P3"
    }
  },
  "oauth": {
    "registration_page": "https://nimiarkisto.nikerabb.it/wiki/Special:OAuthConsumerRegistration/propose"
  },
  "reconciliation": {
    "endpoint": "https://nimiarkisto.nikerabb.it/reconciliation/${lang}/api"
  }
}
```

### Current Results
"Issues" tab is completely empty.
"Preview tab" says:
> This tab shows the first edits (out of 0) that will be made once you upload the changes to Nimiarkisto (dev). You can use facets to inspect the edits on particular items.

Choosing "Upload edits to Wikibase" just briefly shows "Analyzing" popup and displays the "Schema tab".

From OpenRefine logs:
```
openrefine_1        | 16:54:12.836 [                   refine] GET /command/core/get-csrf-token (11552ms)
openrefine_1        | 16:54:12.942 [                   refine] POST /command/wikidata/preview-wikibase-schema (106ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [FormatScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (4ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [InverseConstraintScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [UnsourcedScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [RestrictedPositionScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [QualifierCompatibilityScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [SingleValueScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [DistinctValuesScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [QuantityScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [RestrictedValuesScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [EntityTypeScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [MultiValueScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [DifferenceWithinRangeScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [ConflictsWithScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [ItemRequiresScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [..kidata.qa.EditInspector] scrutinizer [UseAsQualifierScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
openrefine_1        | 16:54:12.946 [                  command] Exception caught (0ms)
openrefine_1        | java.lang.NullPointerException
openrefine_1        |   at org.openrefine.wikidata.qa.EditInspector.inspect(EditInspector.java:127)
openrefine_1        |   at org.openrefine.wikidata.commands.PreviewWikibaseSchemaCommand.doPost(PreviewWikibaseSchemaCommand.java:110)
openrefine_1        |   at com.google.refine.RefineServlet.service(RefineServlet.java:187)
openrefine_1        |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
openrefine_1        |   at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
openrefine_1        |   at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221)
openrefine_1        |   at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
openrefine_1        |   at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
openrefine_1        |   at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
openrefine_1        |   at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
openrefine_1        |   at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
openrefine_1        |   at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
openrefine_1        |   at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
openrefine_1        |   at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
openrefine_1        |   at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
openrefine_1        |   at org.mortbay.jetty.Server.handle(Server.java:326)
openrefine_1        |   at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
openrefine_1        |   at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
openrefine_1        |   at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
openrefine_1        |   at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
openrefine_1        |   at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
openrefine_1        |   at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
openrefine_1        |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
openrefine_1        |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
openrefine_1        |   at java.lang.Thread.run(Thread.java:748)
```
If I use "Export Schema" from the "Extensions: Wikidata" dropdown, it gives this:
```
{
   "itemDocuments":[
      {
         "subject":{
            "type":"wbitemvariable",
            "columnName":"nimilippu"
         },
         "nameDescs":[
            
         ],
         "statementGroups":[
            {
               "property":{
                  "type":"wbpropconstant",
                  "pid":"P10020",
                  "label":"image",
                  "datatype":"external-id"
               },
               "statements":[
                  {
                     "value":{
                        "type":"wbstringvariable",
                        "columnName":"kuvapolku"
                     },
                     "qualifiers":[
                        
                     ],
                     "references":[
                        
                     ]
                  }
               ]
            }
         ]
      }
   ],
   "siteIri":"http://nimiarkisto.fi/entity/",
   "mediaWikiApiEndpoint":"https://nimiarkisto.nikerabb.it/w/api.php"
}
```

### Expected Behavior
To see items on the preview tab.

### Screenshots
![Schema tab](https://user-images.githubusercontent.com/1109395/100128484-012c2680-2e89-11eb-971a-98ef953e5801.png)

### Versions
 - Operating System: Debian 10
 - Browser Version: Google Chrome 87.0.4280.66
 - JRE or JDK Version: openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
 - OpenRefine: Version 3.5-beta [528f4a4]

### Datasets
See https://tinyurl.com/y5xmdjtw for the data I'm trying to use

**Comment by wetneb** [comment]
@Nikerabbit thanks a lot for reporting this. @afkbrb, would you be interested in checking this?

**Comment by afkbrb** [comment]
Sure!

**Comment by afkbrb** [comment]
This NullPointerException bug is caused by changes to extensions/wikidata/src/org/openrefine/wikidata/qa/EditInspector.java in #3060.

**Comment by afkbrb** [comment]
#3355 should be able to fix this.

**Comment by wetneb** [comment]
Oops, sorry I should have pinged @darecoder instead then!

**Comment by wetneb** [comment]
@Nikerabbit the bug should now be fixed on our master branch.

**Comment by Nikerabbit** [comment]
Thanks! I will test it later this week.

**Comment by Nikerabbit** [comment]
Issues & previews are working now.

I am still not able to make a full batch of edits:
* Unable to get owner only consumer login to work
* bot password login works but it gets logged out without way to continue and there are errors in the logs:
`MediaWiki error while editing [badtags]: The tag "openrefine-3.5" is not allowed to be manually applied. (529ms)`
`MediaWiki error while fetching documents to edit [assertuserfailed]: You are no longer logged in, so the action could not be completed. (86ms)`
```
openrefine_1        | 12:14:19.610 [..ting.EditBatchProcessor] Giving up on fetching documents to edit. Skipping 250 remaining edits. (0ms)
openrefine_1        | Exception in thread "Thread-6" java.lang.NullPointerException
openrefine_1        |   at org.openrefine.wikidata.editing.EditBatchProcessor.performEdit(EditBatchProcessor.java:163)
openrefine_1        |   at org.openrefine.wikidata.operations.PerformWikibaseEditsOperation$PerformEditsProcess.run(PerformWikibaseEditsOperation.java:221)
openrefine_1        |   at java.lang.Thread.run(Thread.java:748)
```
* I am also seeing https://github.com/OpenRefine/OpenRefine/issues/3202#issuecomment-733679214

Do all these quality as separate bug reports?

**Comment by wetneb** [comment]
Thanks a lot for your patience and valuable help for ironing out this integration. Yes it would be great to have issues for the first two bullet points - we can use #3202 for the last one.

**Comment by johanricher** [comment]
I am trying out reconciliation and upload with my Wikibase instance and reconciliation service and encountering the same issue as originaly posted above: Issues tab blank, same message in the Preview tab and same Java exception log.

I don't understand why I have this issue since I'm using OpenRefine on the master branch and it's been fixed months ago. Did I miss something?

**Comment by johanricher** [comment]
If that helps, I retried yesterday [with the latest version](https://github.com/OpenRefine/OpenRefine/tree/c574ed867f94a8c06208c1d881d923f5a435e4b4), same thing:
```
13:54:54.767 [                   refine] GET /command/wikidata/login (93836ms)
13:54:54.786 [                   refine] GET /command/core/get-csrf-token (19ms)
13:54:54.835 [                   refine] POST /command/wikidata/preview-wikibase-schema (49ms)
13:54:55.013 [..kidata.qa.EditInspector] scrutinizer [FormatScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (178ms)
13:54:55.013 [..kidata.qa.EditInspector] scrutinizer [InverseConstraintScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
13:54:55.013 [..kidata.qa.EditInspector] scrutinizer [UnsourcedScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
13:54:55.013 [..kidata.qa.EditInspector] scrutinizer [RestrictedPositionScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
13:54:55.013 [..kidata.qa.EditInspector] scrutinizer [QualifierCompatibilityScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
13:54:55.013 [..kidata.qa.EditInspector] scrutinizer [SingleValueScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
13:54:55.013 [..kidata.qa.EditInspector] scrutinizer [DistinctValuesScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
13:54:55.013 [..kidata.qa.EditInspector] scrutinizer [QuantityScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
13:54:55.013 [..kidata.qa.EditInspector] scrutinizer [RestrictedValuesScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
13:54:55.013 [..kidata.qa.EditInspector] scrutinizer [EntityTypeScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
13:54:55.013 [..kidata.qa.EditInspector] scrutinizer [MultiValueScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
13:54:55.013 [..kidata.qa.EditInspector] scrutinizer [DifferenceWithinRangeScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
13:54:55.013 [..kidata.qa.EditInspector] scrutinizer [ConflictsWithScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
13:54:55.013 [..kidata.qa.EditInspector] scrutinizer [ItemRequiresScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
13:54:55.013 [..kidata.qa.EditInspector] scrutinizer [UseAsQualifierScrutinizer] is skipped due to missing of necessary constraint configurations in the Wikibase manifest (0ms)
13:54:55.014 [                  command] Exception caught (1ms)
java.lang.NullPointerException
	at org.openrefine.wikidata.qa.EditInspector.inspect(EditInspector.java:127)
	at org.openrefine.wikidata.commands.PreviewWikibaseSchemaCommand.doPost(PreviewWikibaseSchemaCommand.java:110)
	at com.google.refine.RefineServlet.service(RefineServlet.java:187)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

[My setup is documented here](https://gitlab.huma-num.fr/eurhisfirm/eurhisfirm-wikibase-openrefine/).

**Comment by afkbrb** [comment]
Hi @johanricher, it seems that you didn't rebuild OpenRefine after pulling the lastest version.

In the log you provided, it says the NPE was caused by `inspect(EditInspector.java:127)`, but the source code has been changed to 

https://github.com/OpenRefine/OpenRefine/blob/efca0bee2c42311b5a28b094992aaaa14ee3c793/extensions/wikidata/src/org/openrefine/wikidata/qa/EditInspector.java#L127-L130

So line 127 won't encounter an NPE now.

To rebuild, use `refine.bat build` on Windows or `./refine build` on Linux/Mac.

**Comment by johanricher** [comment]
Thank you so much @afkbrb! I ran `./refine build` then ran OR again and the issue was gone.

I'm really sorry about this, I didn't know a rebuild was necessary. I'm not familiar with Java and it's not specified in the README, even though it's probably obvious for people more experienced than me!

This issue can be closed again as far as I'm concerned.
