### ISSUE TITLE
Import from public Google spreadsheet doesn't work

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#461]
_Original author: tfmorris (October 12, 2011 21:47:01)_

Attempting to import a public Google data spreadsheet by pasting the URL (
https://docs.google.com/spreadsheet/ccc?key=0AuCc2KRWCBN7dDlSSVBpcU5IZnVTWW5TVzhqY3V0WGc) into the &quot;Web Addresses&quot; tab of the importer UI causes Refine to given an error saying it can't parse the Excel file.  If you click on one of the tabs for a text based format, you can see that the text that it fetched is actually HTML for a redirect:

&lt;TITLE&gt;Moved Temporarily&lt;/TITLE&gt;
4. &lt;/HEAD&gt;
5. &lt;BODY BGCOLOR=&quot;#FFFFFF&quot; TEXT=&quot;#000000&quot;&gt;
6. &lt;H1&gt;Moved Temporarily&lt;/H1&gt;
7. The document has moved &lt;A HREF=&quot;http://www.google.com/url?q=https://docs.google.com/spreadsheet/ccc?key&#37;3D0AuCc2KRWCBN7dDlSSVBpcU5IZnVTWW5TVzhqY3V0WGc&#37;26pref&#37;3D2&amp;amp;sa=p&quot;&gt;here&lt;/A&gt;.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=461_

**Comment by wetneb** [comment]
This still does not work because they have changed their API.

**Comment by wetneb** [comment]
Solved by the revamp of the google extension by @jackyq2015

**Comment by adivea** [comment]
I am still having issues with importing public google sheets to OpenRefine. When I paste in a googlesheet URL I get routed to sign in, and then get the "Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In." message. I don't see where I can permit the OR to be verified by Google.

![image](https://user-images.githubusercontent.com/7598517/76210501-8c369500-6204-11ea-9964-990ddd0993ac.png)

**Comment by wetneb** [comment]
@adivea which version of OpenRefine are you using? This should be fixed in 3.3.

**Comment by adivea** [comment]
Sorry, I am still on the 3.1
Will download 3.3 now and test.
A.

*Dr Adela Sobotkova*
FAIMS Project - Co-Director
adela@fedarch.org
Center for Digital History Aarhus (CEDHAR <http://cas.au.dk/cedhar>) -
Co-Director
adela@cas.au.dk
+45 41140011
