### ISSUE TITLE
OpenRefine not showing projects in Open projects tab

### ISSUE THREAD

**Issue by RhydianLLGC** [OpenRefine/OpenRefine#5111]
Hi, I tried to change the max memory of Openrefine so I could use a certain file (which wouldn't load before because it was too big).  I changed the openrefine.l4j.ini and changed it in there so it went to 4GB rather than 1GB which is the default.  After reloading OpenRefine all of the projects that were in there before are now gone and as you can see in the screenshot below nothing is showing up.  When clicking browse workspace directory it shows the usual 'App data/roaming/OpenRefine' and it does have projects in there like I have seen with others but nothing shows up when going to the 'Open Projects' tab.
I have also seen a similar issue where the fix was to put in the directory location in the openrefine.l4j.ini file but that did nothing to help the problem.

Any ideas on why this is happening? 

### Screenshots

![OpenRefine_No_Projects](https://user-images.githubusercontent.com/109804696/180443191-3f5bd4b6-8558-45ae-a7e8-178faa207b82.PNG)

### Versions
 - Operating System: Windows 10
 - Browser Version: Google Chrome 103.0.5060.134
 - JRE or JDK Version: Java 8.0.3410.10
 - OpenRefine: 3.5.2

**Comment by elebitzero** [comment]
Hey @RhydianLLGC,

There was an issue (#4972) that was fixed in 3.6.0 where the project list would not load if there was a malformed project.  You could try version 3.6.0 and see if that resolves your issue.  Please report back if you try that.

Also, you may check the JavaScript developer console and see if there any exceptions. If you do, please post them on this issue.

**Comment by AtesComp** [comment]
Is **openrefine.l4j.ini** the Log4J config file?

Instead, edit the **refine.ini** file for Java memory management.

However, it is odd that changing the **openrefine.l4j.ini** would result in such behavior.

**Comment by RhydianLLGC** [comment]
Hi @elebitzero, 
I have just updated to version 3.6.0 and changed the memory to 4GB again and the open projects bug is still there?

**Comment by AtesComp** [comment]
@RhydianLLGC,
Does it work when you update the refine.ini file?  Reset the openrefine.l4j.ini to the original settings.

**Comment by elebitzero** [comment]
I am on Windows 10 as well, I downloaded OpenRefine 3.6.0, and changed the max memory from 1400M to 4096M in the refine.ini file:

# Maximum JVM heap (memory) and max form size allocations
#REFINE_MAX_FORM_CONTENT_SIZE=1048576
REFINE_MEMORY=4096M

It is running fine from the command line, and I see the project list in the UI:

```
C:\software\openrefine-3.6.0>refine.bat run
Using refine.ini for configuration
Java 17 (17.0.2)
Getting Free Ram...
21:58:50.093 [            refine_server] Starting Server bound to '[127.0.0.1:3333](http://127.0.0.1:3333/)' (0ms)
21:58:50.097 [            refine_server] refine.memory size: 4096M JVM Max heap: 4294967296 (4ms)
21:58:50.116 [            refine_server] Initializing context: '/' from 'C:\software\openrefine-3.6.0\webapp' (19ms)
21:58:51.788 [                   refine] Starting OpenRefine 3.6.0 [ff7de4d]... (1672ms)
21:58:51.789 [                   refine] initializing FileProjectManager with dir (1ms)
```


Please note if there are any errors on the command line or the JavaScript console in your browser. On Chrome, press CTRL+SHIFT+I and click on console tab.

I agree with @AtesComp, that you should be modifying refine.ini and not openrefine.l4j.ini

**Comment by thadguidry** [comment]
This is likely not a bug, but a workspace (data directory) issue.  If you need further help troubleshooting, please contact us on our mailing list.
