### ISSUE TITLE
Cursor suggests action-on-click when over a column name even though there is no action

### ISSUE THREAD

**Issue by jquartel** [OpenRefine/OpenRefine#5977]
I often need to copy the name of a column and although this is simple enough by selecting the text of the column name with a double-click or click-drag, I notice that the cursor turns to the gloved finger (the same type of cursor you get when over a url link) when in this vicinity, suggesting that there might be some action on a single click. As far as I can tell, however, there is only an action when you click on the triangle-in-square next to the column name (i.e. to bring up the column actions menu). So although this is a very minor thing and there is no loss of functionality, I think it would make the interface look more consistent and clean if the cursor were the I-bar type (for text selection) rather than the finger when it is just over the column name (and only switch to the finger when over the triangle for the action menu).

**Comment by wetneb** [comment]
I think some recent changes happened in this area so I think if you try the development version you will not have the finger-type cursor anymore (but not the l-bar type yet).

**Comment by Abbe98** [comment]
This has been fixed on the master branch: #5869.

**Comment by jquartel** [comment]
I'm not sure why this ticket was closed as I'm still seeing this issue. Just tested

Open Refine Version 3.7.6
with both
Chrome Version 117.0.5938.149 , and Safari Version Version 17.0 (18616.1.27.111.22, 18616)

**Comment by jquartel** [comment]
Ah, great thanks!
